#!/bin/bash

cat <<"EOF"
                                ___           ___                               
                               /\  \         /\__\                              
      ___         ___         |::\  \       /:/ _/_                             
     /\__\       /\__\        |:|:\  \     /:/ /\__\                            
    /:/  /      /:/__/      __|:|\:\  \   /:/ /:/ _/_                           
   /:/__/      /::\  \     /::::|_\:\__\ /:/_/:/ /\__\                          
  /::\  \      \/\:\  \__  \:\~~\  \/__/ \:\/:/ /:/  /                          
 /:/\:\  \      ~~\:\/\__\  \:\  \        \::/_/:/  /                           
 \/__\:\  \        \::/  /   \:\  \   ___  \:\/:/  /                            
      \:\__\       /:/  /     \:\__\ /\  \  \::/  /                             
       \/__/       \/__/___    \/__//::\  \  \/__/                              
                       /\__\       /:/\:\  \                                    
                      /:/  /      /:/  \:\  \                                   
                     /:/__/      /:/__/ \:\__\                                  
                    /::\  \      \:\  \ /:/  /                                  
                   /:/\:\  \      \:\  /:/  /                                   
                   \/__\:\  \      \:\/:/  /                                    
                        \:\__\      \::/  /                                     
      ___                \/__/___    \/__/  ___                         ___     
     /\  \                   /\__\         /\  \                       /\__\    
    /::\  \     ___         /:/  /        /::\  \                     /:/ _/_   
   /:/\:\__\   /\__\       /:/  /        /:/\:\  \                   /:/ /\__\  
  /:/ /:/  /  /:/__/      /:/  /  ___   /:/  \:\  \   ___     ___   /:/ /:/ _/_ 
 /:/_/:/  /  /::\  \     /:/__/  /\__\ /:/__/ \:\__\ /\  \   /\__\ /:/_/:/ /\__\
 \:\/:/  /   \/\:\  \__  \:\  \ /:/  / \:\  \ /:/  / \:\  \ /:/  / \:\/:/ /:/  /
  \::/__/     ~~\:\/\__\  \:\  /:/  /   \:\  /:/  /   \:\  /:/  /   \::/_/:/  / 
   \:\  \        \::/  /   \:\/:/  /     \:\/:/  /     \:\/:/  /     \:\/:/  /  
    \:\__\       /:/  /     \::/  /       \::/  /       \::/  /       \::/  /   
     \/__/       \/__/       \/__/         \/__/         \/__/         \/__/    


EOF




VIMRC=".vimrc"
VIMDIR=".vim"


<<VIMRC_CONFIGURATION

""VIM_CONFIG_START

"Basic syntax ----------------------------------------------------------------------

syntax on
set number 
set tabstop=3		""TabSize of 3  
set shiftwidth=3 	""Indentation fo 3  
set softtabstop=0 ""Enabeling it will remplace tabs by spaces in insert mode not cool
set noexpandtab 	""Enabeling it will remplace tabs by spaces not cool 

"-----------------------------------------------------------------------------------



"NerdTree --------------------------------------------------------------------------

"autocmd vimenter * NERDTree "For auto activating nerd tree when vim opens 
map <C-n> :NERDTreeToggle<CR>  
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif ""autoClose wim when only the NerdTree Window IS open 

"------------------------------------------------------------------------------------

""VIM_CONFIG_END

VIMRC_CONFIGURATION



printf "\e[93m================================================== GOING HOME ==================================================\e[32m\n\n"
cd ~
cp PiConf Temp.txt



printf "\e[31m================================================== INSTALLING GIT================================================\e[32m\n"
sudo apt-get install git-core 
printf "\e[36m================================================== FINISHED INSTALLING GIT =======================================\e[32m\n\n"




printf "\e[31m================================================== INSTALLING VIM ================================================\e[32m\n"

sudo apt-get -y install vim
git clone https://github.com/scrooloose/nerdtree.git


if [ -f $VIMRC ];
then
   printf "\e[95mFile : $VIMRC exists Making a Backup\e[32m\n"
     mv $VIMRC  "$VIMRC".bak
     touch vimconfig.txt
else
   printf "\e[95mCreatting file : $VIMRC\n"
   touch vimconfig.txt
fi

if [ -d "$VIMDIR" ]; 
then 
	printf "\e[95mDirectory : $VIMDIR exists Making a Backup\e[32m\n"
	sleep 1 

	if [ -d "$VIMDIR""_bak" ];
	then
		printf "\e[95mBackup Directory Allredy Exists : Replacing\e[32m\n"
		sudo rm -r $VIMDIR"_bak"
	fi
	
	mv $VIMDIR $VIMDIR"_bak"
	sudo mkdir $VIMDIR
else 
	printf "\e[95mCreating directory : $VIMDIR \e[32m\n"
	sudo mkdir $VIMDIR
fi


sed -n '/""VIM_CONFIG_START/,/""VIM_CONFIG_END/w vimconfig.txt' Temp.txt
sed -i '/VIM_CONFIG_END/,$d' vimconfig.txt

mv vimconfig.txt $VIMRC

sudo cp -a nerdtree/. $VIMDIR
sudo rm -r nerdtree/

printf "\e[36m================================================== FINISHED INSTALLING VIM =======================================\e[32m\n\n"



printf "\e[31m================================================== INSTALLING C RELATIES =========================================\e[32m\n"
sudo apt-get install gcc
printf "\e[36m================================================== FINISHED INSTALLING CRELATIVES ================================\e[32m\n\n"



sudo rm Temp.txt
printf "\e[95mfinished\e[32m\n"
